chore: dprint formatting Signed-off-by: Riccardo Nalgi <riccardo.nalgi@secomind.com>

diff --git a/.github/workflows/build-workflow.yaml b/.github/workflows/build-workflow.yaml
--- a/.github/workflows/build-workflow.yaml
+++ b/.github/workflows/build-workflow.yaml
@@ -4,8 +4,8 @@ on:
   # Run when pushing to stable branches
   push:
     branches:
-    - 'master'
-    - 'release-*'
+      - "master"
+      - "release-*"
   # Run on branch/tag creation
   create:
   # Run on pull requests
@@ -22,36 +22,36 @@ jobs:
     env:
       MIX_ENV: ci
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v4
-      with:
-        path: deps
-        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
-    - uses: actions/cache@v4
-      with:
-        path: _build
-        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
-    - id: plt_cache
-      uses: actions/cache@v4
-      with:
-        path: dialyzer_cache
-        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-dialyzer_cache-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-dialyzer_cache-
-    - uses: erlef/setup-beam@v1.18
-      with:
-        otp-version: ${{ env.otp_version }}
-        elixir-version: ${{ env.elixir_version }}
-    - name: Install Dependencies
-      run: mix deps.get
-    - name: Create PLTs dir
-      if: ${{steps.plt_cache.outputs.cache-hit != 'true'}}
-      run: mkdir -p dialyzer_cache && mix dialyzer --plt
-    - name: Run dialyzer
-      # FIXME: This should be set to fail when dialyzer issues are fixed
-      run: mix dialyzer || exit 0
+      - uses: actions/checkout@v4
+      - uses: actions/cache@v4
+        with:
+          path: deps
+          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
+      - uses: actions/cache@v4
+        with:
+          path: _build
+          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
+      - id: plt_cache
+        uses: actions/cache@v4
+        with:
+          path: dialyzer_cache
+          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-dialyzer_cache-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-dialyzer_cache-
+      - uses: erlef/setup-beam@v1.18
+        with:
+          otp-version: ${{ env.otp_version }}
+          elixir-version: ${{ env.elixir_version }}
+      - name: Install Dependencies
+        run: mix deps.get
+      - name: Create PLTs dir
+        if: ${{steps.plt_cache.outputs.cache-hit != 'true'}}
+        run: mkdir -p dialyzer_cache && mix dialyzer --plt
+      - name: Run dialyzer
+        # FIXME: This should be set to fail when dialyzer issues are fixed
+        run: mix dialyzer || exit 0
 
   test-coverage:
     name: Build and Test
@@ -62,30 +62,30 @@ jobs:
     env:
       MIX_ENV: test
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v4
-      with:
-        path: deps
-        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
-    - uses: actions/cache@v4
-      with:
-        path: _build
-        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
-    - uses: erlef/setup-beam@v1.18
-      with:
-        otp-version: ${{ env.otp_version }}
-        elixir-version: ${{ env.elixir_version }}
-    - name: Install Dependencies
-      run: mix deps.get
-    - name: Check formatting
-      run: mix format --check-formatted
-    - name: Compile
-      run: mix compile
-    - name: Test and Coverage
-      run: mix coveralls.json  --exclude wip -o coverage_results
-    - uses: codecov/codecov-action@v5
-      name: Upload Coverage Results to CodeCov
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
+      - uses: actions/checkout@v4
+      - uses: actions/cache@v4
+        with:
+          path: deps
+          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
+      - uses: actions/cache@v4
+        with:
+          path: _build
+          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-_build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
+      - uses: erlef/setup-beam@v1.18
+        with:
+          otp-version: ${{ env.otp_version }}
+          elixir-version: ${{ env.elixir_version }}
+      - name: Install Dependencies
+        run: mix deps.get
+      - name: Check formatting
+        run: mix format --check-formatted
+      - name: Compile
+        run: mix compile
+      - name: Test and Coverage
+        run: mix coveralls.json  --exclude wip -o coverage_results
+      - uses: codecov/codecov-action@v5
+        name: Upload Coverage Results to CodeCov
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
